NUMPY


In [1]:
mix_list = [1,2,3,4.1,"a"]

In [2]:
import numpy as np

In [3]:
np_mix_list = np.array(mix_list)
np_mix_list

array(['1', '2', '3', '4.1', 'a'], dtype='<U32')

In [5]:
zero_array = np.array(50)
zero_array
type(zero_array)

numpy.ndarray

In [6]:
one_array = np.array([1,2,3])

In [8]:
two_array = np.array([[1,2,3], [4,5,6]])
type(two_array)
two_array

array([[1, 2, 3],
       [4, 5, 6]])

Properties of Numpy


In [10]:
my_np_array = np.array([1,2,4,5,8])
my_np_array

array([1, 2, 4, 5, 8])

In [11]:
my_np_array.dtype

dtype('int32')

In [12]:
my_np_array.ndim

1

In [13]:
my_np_array.shape

(5,)

In [14]:
my_np_array.size

5

Prepopulate Arrays

In [15]:
zeros = np.zeros(5)
zeros

array([0., 0., 0., 0., 0.])

In [16]:
zeros.dtype

dtype('float64')

In [21]:
zeros = np.zeros(5, dtype=int)
zeros

array([0, 0, 0, 0, 0])

In [22]:
np.empty(5)

array([0., 0., 0., 0., 0.])

In [25]:
np.arange   

array([], dtype=int32)

2D Array

In [40]:
l1 = [1,2,3]
l2 = [4,5,6]
l3 = [7,8,9]
new_array = np.array([l1,l2])

In [41]:
new_array

array([[1, 2, 3],
       [4, 5, 6]])

In [32]:
new_array.shape

(3, 3)

In [34]:
a1 = np.array([1,2,3,4,5])

In [38]:
a2 = a1.copy()

In [45]:
updated_array = new_array.reshape(3,2)
updated_array

array([[1, 2],
       [3, 4],
       [5, 6]])

Aruthmetic using Numpy

In [ ]:
# Exercise randonly 1 lakh numbers, sum vs np.sum with %timeit

In [67]:
import timeit
import numpy as np

test = np.random.randint(1, 1000, 100000)
timeit.timeit(np.sum(test > 500))
#sum(test > 500)

ValueError: stmt is neither a string nor callable

In [61]:
### Solving Linear Algebra equations
# 20x + 10 y = 350
# 17x +22y = 500

A = np.array([[20,10], [17,22]])
B = np.array([350,500])

In [62]:
np.linalg.solve(A,B)

array([10., 15.])

In [64]:
x = np.eye(5)
x

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])